# Generated by Django 4.2.6 on 2023-12-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
