# Generated by Django 4.2.7 on 2023-12-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hospital_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='doctors', to='app.hospital'),
        ),
    ]
