# Generated by Django 4.2.6 on 2023-12-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_doctor_hospitals_doctor_hospitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
    ]
