# Generated by Django 4.2.7 on 2023-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_specialization_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
